import ApplicationController from './application_controller';

export default class extends ApplicationController {
    /*
    Show a loading spinner. If no URL is provided, directly embed an SVG
     */
    static values = {
        url: String, // SVG url
        size: Number, // With and Height
    }

    connect() {
        const size = this.hasSizeValue ? this.sizeValue : 40;
        console.log(size)
        if (this.hasIconValue) {
            const img = document.createElement('img')
            img.src = this.urlValue;
            this.element.appendChild(img);
        } else {
            this.urlValue = `
           <?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: rgba(255, 255, 255, 0) none repeat scroll 0% 0%; display: block; shape-rendering: auto;" width="${size}px" height="${size}px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
<path d="M10 50A40 40 0 0 0 90 50A40 42 0 0 1 10 50" fill="#e15b64" stroke="none">
  <animateTransform attributeName="transform" type="rotate" dur="1s" repeatCount="indefinite" keyTimes="0;1" values="0 50 51;360 50 51"></animateTransform>
</path>
<!-- [ldio] generated by https://loading.io/ --></svg>
           `
            this.element.innerHTML = this.urlValue;
        }
        this.loading();
    }

    loading() {
        this.element.style.display = 'inline-block'
    }

    loaded() {
        this.element.style.display = 'none'
    }
}
